version: '3.8'

services:  
  client:
    build:
      context: src/
      args:
        - APPNAME=client
    entrypoint: client
    env_file:
      - .env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    volumes:
      - "./src/client:/src/client"
    depends_on:
      - server

  server:
    build:
      context: src/
      args:
        - APPNAME=server
    entrypoint: server
    env_file:
      - .env
    expose:
      - ${SERVER_PORT}
    volumes:
      - "./src/server:/src/server"      

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluentd

  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch: