version: '3.8'

services:  
  client:
    container_name: client
    build:
      context: ${BASE}/src/
      args:
        - APPNAME=client
    logging:
      driver: "fluentd"
      options:
        tag: "docker.{{.Name}}"
        fluentd-address: localhost:24224
        fluentd-async: "true"
        fluentd-buffer-limit: "8192"
        fluentd-sub-second-precision: "true"
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ${BASE}/src/
      args:
        - APPNAME=server
    expose:
      - 8000
    logging:
      driver: "fluentd"
      options:
        tag: "docker.{{.Name}}"
        fluentd-address: localhost:24224
        fluentd-async: "true"
        fluentd-buffer-limit: "8192"
        fluentd-sub-second-precision: "true"
    depends_on:
      - otel-collector

  otel-collector:
    container_name: otel-collector
    build: ${BASE}/otel-collector
    expose:
      - 1888   # pprof extension
      - 4317   # OTLP gRPC receiver
      - 13133  # health_check extension
      - 55679  # zpages extension
    depends_on:
      - tempo

  fluentbit:
    build: ${BASE}/fluent-bit
    container_name: fluentbit
    ports:
      - 24224:24224
    depends_on:
      - loki

  tempo:
    container_name: tempo
    build: ${BASE}/tempo
    expose:
      - 3200   # tempo
      - 4317   # otlp grpc
    depends_on:
      - grafana
      - prometheus

  loki:
    container_name: loki
    build: ${BASE}/loki 
    ports:
      - 3100
    depends_on:
      - grafana

  prometheus:
    container_name: prometheus
    build: ${BASE}/prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    expose:
      - 9090

  grafana:
    build: ${BASE}/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ${BASE}/grafana/.env
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - 8081
    environment:
      ENABLE_METRICS: "true"

volumes:
  grafana:
