version: '3.8'

services:  
  client:
    build:
      context: ${BASE}/src/
      args:
        - APPNAME=client
    entrypoint: client
    env_file:
      - .env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:${FLUENTBIT_PORT}
        tag: "docker.{{.Name}}"
    depends_on:
      - server

  server:
    build:
      context: ${BASE}/src/
      args:
        - APPNAME=server
    entrypoint: server
    env_file:
      - .env
    expose:
      - ${SERVER_PORT}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:${FLUENTBIT_PORT}
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentbit

  fluentbit:
    build: ${BASE}/fluent-bit
    container_name: fluentbit
    ports:
      - "${FLUENTBIT_PORT}:${FLUENTBIT_PORT}"
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100

  grafana:
    build: ${BASE}/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - 8081
    environment:
      ENABLE_METRICS: "true"

volumes:
  grafana:
